### ISSUE TITLE
Error at $My.Title

### ISSUE THREAD

**Issue by joaociocca** [iRon7/Write-Log#2]
Não é possível chamar um método em uma expressão de valor nulo.
No script.ps1:226 caractere:1
`+ $My.Title = $My.Synopsis.Trim().Split("`r`n")[0].Trim()`
`+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`
`    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException`
`    + FullyQualifiedErrorId : InvokeMethodOnNull`
`Error at 226,1: Não é possível chamar um método em uma expressão de valor nulo.`

Error translates to "It's not possible to call a method in an expression of null value".

**Comment by iRon7** [comment]
Thanks for your feedback. I presume this because you do not have an
header/synopsis defined.
I will look into this tomorrow.

Op 22 jun. 2017 5:41 PM schreef "João Umberto Ciocca de Almeida" <
notifications@github.com>:

**Comment by joaociocca** [comment]
I added the .Synopsis, .Description and .Notes sections - new error found!

`Não é possível chamar um método em uma expressão de valor nulo.`
`No \\10.0.2.225\STI\CSI\Monitoracao\sysgray\windows_sysmon_sidecar.ps1:232 caractere:86`
`+ ... ", 2); If ($Note[0].Trim()) {$My[$Note[0].Trim()] = $Note[1].Trim()}}`
`+                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`
`    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException`
`    + FullyQualifiedErrorId : InvokeMethodOnNull`
`Error at 232,86: Não é possível chamar um método em uma expressão de valor nulo.`

**Comment by iRon7** [comment]
The general idea (and how I have tested it) is to start with the complete
framework, personalize the header and put your main code in the main
function.
Anyway, I am also working on a module version (.psm1).
Anyway, I will check tomorrow how I can avoid these type of errors.

Op 22 jun. 2017 6:23 PM schreef "João Umberto Ciocca de Almeida" <
notifications@github.com>:

**Comment by iRon7** [comment]
I just uploaded a new version (01.00.05) to fix both errors.
But I would still recommend to use (and customize) the given header template as that will e.g. automatically put your script version in first line of your log session.

**Comment by joaociocca** [comment]
Ok, no errors now! =D thanks @iRon7! 

Quick doubt - how do I log what programs do on the main script, specially in the case of errors? I looked at the documentation and couldn't find anything about that. Obviously, my first idea would be to output to a variable and then log that - but I feel like there's a better way to do it that I'm missing...

**Comment by iRon7** [comment]
I am not sure whether I understand the question but let me clarify two thing that might answer it:
1) Unlike several other languages (like VBScript), PowerShell needs to read a function prior it can be called. Meaning that you can use the `Log` function only after the `Function Log {...` is defined which is in fact at the bottom of the template I supplied (meaning here you can place any Log call at the "root" -outside any function- in your script). As it is a little inconvenient to always have to scroll to the bottom to manage your actual script I created a `Main {}` function at the to which is called from the bottom.  
Note 1) The functions, I have set up are global (`Global:LogWrite`) this means that they are also available from the host ones you called the framework. (The log variables although, are not global, meaning that it will not remember e.g. the `LogFile` after the framework has been called).  
Note 2) You can still place your own functions anywhere in the "root" (prior the `Main` function is called at the bottom) and call them from the `Main {}` function.
2) Depending on the error and the ErrorAction parameter (see e.g. https://blogs.technet.microsoft.com/heyscriptingguy/2014/07/09/handling-errors-the-powershell-way/), the script might continue. The next log call will capture the error and record this in the log file, e.g.:  
	`Get-ChildItem NoSuchFile.txt -ErrorAction SilentlyContinue`
	`Log "Test"`
Will record the following in the log file:
	`Error at 19,15: Cannot find path 'C:\Users\Write-Log\NoSuchFile.txt' because it does not exist.`
	`11:00:21.37	Test`
Note that if the script exits due to an critical error there is no way anymore for the Log function to capture the error (in most cases you can also can prevent the script to break with a "Try {} Catch {}" syntax.

**Comment by joaociocca** [comment]
Yeah, I've been trying to run a get-service that keeps eluding me. The idea is exactly to find out if it's installed/running, and act on that, but I didn't want the user to see the raw error, like
`Error at 64,31: Não é possível localizar qualquer serviço com o nome de serviço 'teste'.`
(translates to "not possible to find any service with service name 'test'.")

The way I'm making this script, if there's no service, it'll install. if there is, it'll update configurations. If I run the following command on it's own, it works
`$variable = get-service blabla -ErrorAction SilentlyContinue -ErrorVariable getError`
This way, nothing shows up and $getError is populated with the error. But that's only outside the script - when I run inside the logging framework, I still get the "Error at 64,31" =(

**Comment by iRon7** [comment]
Hello João
The definition for the `-ErrorVariable` parameter is: Specifies a variable that stores errors from the command during processing. _This variable is populated in addition to $error._
As it is populated in the `$Error` object, it is picked up by the `Log` function as a new error. You can prevent this by adding a line such as: `If ($GetError) {$Error.Remove($Error[0])}`  
I will also investigate adding a new parameter like `-FlushErrors` for future releases.
